### ISSUE TITLE
Unable to use ```lint-fix```and remove IBM prefix when working via the tutorials in Angular

### ISSUE THREAD

**Issue by ENate** [carbon-design-system/carbon-components-angular#2687]
## Detailed description
I followed the tutorial on your website on how to design an angular carbon design using the tutorial guides provided on your website.
> Describe in detail the issue you're having.
- I noticed that a number of commands do not work on Angular 16.0+ For instance, 
- ``` ng g component header --lint-fix```does not work with the ```--lint-fix```, and I do not know what you meant by adding the following code 
- ```
 import Notification20 from '@carbon/icons/es/notification/20';
import UserAvatar20 from '@carbon/icons/es/user--avatar/20';
import AppSwitcher20 from '@carbon/icons/es/app-switcher/20';
```
inside ```src/app/header/app.modules.ts ```since we need 1 ``àpp.module.ts```in this case.  Does this mean we need another ```src/app/header/app.modules.ts

```after creating the header component?

Also, running step 1 of the tutorial using```npm start ```resulted in the following errors: 
```
Error: src/app/header/header.component.html:6:9 - error NG8001: 'ibm-header-action' is not a known element:
1. If 'ibm-header-action' is an Angular component, then verify that it is part of this module. 
2. If 'ibm-header-action' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
```
I added ```CUSTOM_ELEMENTS_SCHEMA```to the ``ǸgModules.schema```in the ```app.module.ts```folder but still go the error.
> Is this a feature request (new component, new icon), a bug, or a general issue?
General issue
> Is this issue related to a specific component?
Yes it is also related to UI Shell Header component. Unable to remove the ``ÌBM```prefix in the header element of this component.

It seems. But I imagine it has to do with the Angular version, maybe.

> What did you expect to happen? What happened instead? What would you like to see changed?

To see the output of the tutorial guide for step 1

> What browser are you working in?
Google-chrome, Firefox, Brave
> What version of the Carbon Design System are you using?
5.+
> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Personal project

## Steps to reproduce the issue

<!--
Please try to re-create the issue using our Codesandbox template available here:
https://codesandbox.io/s/carbon-components-angular-0129r494ql

This helps reduce the issue to an isolated case that helps us out when debugging.
If you're able to reproduce using the codes-and-box link above, please include the
link in addition to the steps to reproduce. Thanks so much!

If your use case is too complex to be replicated in codes-and-box, you can provide
a link to a public GitHub repo where you replicated the issue, along with the steps
it takes.
-->

<!-- [Codesandbox](<url>) -->

1. Step one
2. Step two
4. Step three
5. etc.

## Additional information

* Screenshots or code
* Notes

**Comment by nipun005** [comment]
Hi , if "ng g component header --lint-fix" is not working together- You can simply use-

ng g component header

Above command will create a component named- header in your application,

"lint-fix" command was nothing but it will fix your formatting or basic issues in code.

So, For it you can run separate command as- "ng lint --fix"

Talking about your 2nd error where you are getting -  'ibm-header-action' is not a known element:

To Fix it- Try importing "HeaderModule" in your app.module.ts file and provide it in imports array, then this error should remove

**Comment by ENate** [comment]
Thanks I will also want to know if I can remove the IBM prefix from the header or this must be added to all header (UI shell ) components?

**Comment by ENate** [comment]
@nipun005 it will be great to remove the IBM prefix because I want to use the components for a personal project. I thought merely using something like cds-header-action will do away with it. Of course in my opinion, making it possible for us (the users) to remove the IBM prefix when using it for personal projects will increase the outreach. So, it will be great if you make the changes and submit the PR. Thanks again.

**Comment by nipun005** [comment]
Hi @ENate, Below PR has been raised against current issue, for removal of "ibm" prefix from header-action component.
https://github.com/carbon-design-system/carbon-components-angular/pull/2723

Not sure, But if It is required to Update the heading/subject of this current issue #2687 so that it can be understood that what we fixed as part of this issue, You can do that.

Thanks.

**Comment by Akshat55** [comment]
@ENate This is because the tutorial is not updated for Angular 16+ (Which is specifically Carbon 11+). The tutorial is still in our backlog unfortunately.

You can refer to v10 tutorial which in most cases is similar. https://v10.carbondesignsystem.com/developing/angular-tutorial/overview/

We plan to work on angular tutorial next year.

**Comment by Akshat55** [comment]
The `ibm` prefix will **not** be removed from the component as that would be a breaking change. 

You can opt to use `cds`  (carbon-design-system) prefix in v11, but tutorial currently is incomplete for v11. The ibm prefix will be removed in carbon-components-angular@v6

**Comment by ENate** [comment]
Hi @Akshat55 I did use cds prefix for versions later than 15+ but still see the ibm prefix after building the app.

**Comment by Akshat55** [comment]
If you're using cds prefix, I'm assuming you're using carbon-components-angular@v5. 

Could you compare your project code to our starter demo application to see if you have the correct dependencies:

https://github.com/carbon-design-system/carbon-angular-starter

**Comment by ENate** [comment]
Thanks but I still see IBM[Platform] at the top left hand side of the header- I will like to use mine or remove it. It seems this is not possible as you stated earlier?

**Comment by Akshat55** [comment]
@ENate Oh sorry, I got confused by the PR that was created.

To remove the `IBM` from the header, you can pass in your own brand, it defaults to `IBM`. You can use the following code snippet:

```html
<!--  You can even set the brand/name to an empty string -->
<cds-header name="[Platform]" brand="Your brand here">
   ...
</cds-header>
```


This will result in the following:
![image](https://github.com/carbon-design-system/carbon-components-angular/assets/38994122/d585a278-d8ff-4bc7-88a7-278d90f5c894)

**Comment by ENate** [comment]
Thanks a lot for this. I will like to contribute too. Seems there is nothing available for first good issue or similar

**Comment by ENate** [comment]
Hi @Akshat55 do you have any idea why I get this warning when I use carbon-design-components?
```
Warning: /home/git-repos/carbon-angular-starter/node_modules/carbon-components-angular/fesm2020/carbon-components-angular-datepicker.mjs depends on 'flatpickr/dist/l10n/index'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
I obviously did search and some answers were suggested in the Angular doc. But they do not work. (It was about changing some browser stuffs).
```
Thanks

**Comment by ENate** [comment]
Thanks a lot!

**Comment by ENate** [comment]
Hi @Akshat55 I wanted to see if I can add menu items as a drop down list under icons. For instance, using an App Switcher, I can add a side panel. But it seems the option of adding sub menu items under an icon in the UI global header is not available in carbon icons when using Angular?
